Use fact() function for all os.distro.* facts
puppetlabs/puppetlabs-apt pull request #1017
Opened 2022-02-24 12:18 UTC by root-expert

* On Puppet 6 facter 3.x requires `lsb-release` to resolve os.distro.* facts. Using $facts hash cause errors like "Evaluation Error: Operator '[]' is not applicable to an Undef Value." because os.distro is undefined causing the catalog to fail. Use fact() to identify Undef facts and throw an error to the user.

Releated:

* https://github.com/voxpupuli/beaker-hostgenerator/pull/244

2022-02-24 12:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/puppetlabs-apt?pullRequest=1017) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/puppetlabs-apt?pullRequest=1017) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/puppetlabs-apt?pullRequest=1017) it.</sub>

2022-02-24 16:51 UTC, kenyon submitted a review, later dismissed

2022-03-06 20:12 UTC, smortex reviewed
Hum… :thinking:  This is a good start but not enough I think.

This is replacing a hard failure with a cryptic error message by no failure (at the puppet level) but a broken configuration (at the apt level) when running on a system without the 'apt-transport-https' package but 'https://' repositories (and all sources will lack a release which is probably not good BTW).

We can't add a dependency on `lsb-release` at this level since it is needed before the catalog is computed (i.e. already too late).

My guess is that we should rather fail hard with a clear error message when we detect that `fact('os.distro.codename')` is `undef` with a message like `Cannot determine the distribution codename. Older versions of Facter rely on lsb-release to fetch it, is it installed?`.  Maybe in the `apt` class if all classes include it.

What do you think?

2022-03-06 21:13 UTC, root-expert commented
Yes that's probably the correct way and I have opened a PR on the puppetlabs-apt repo but nobody has gotten around it just yet.

I've seen some more modules using os.distro facts but the good thing is they are limited.

2022-03-06 21:14 UTC, root-expert commented
I don't think it's a cryptic error, it clearly states that a specific parameter must be declared in order for it to work 🤔 

It fails to auto-detect the distro so the user must explicitly set it (or install lsb-release)

2022-03-06 22:52 UTC, smortex commented
What I call a *cryptic* error message is [the following when adding a random resource](https://github.com/voxpupuli/puppet-elasticsearch/runs/5374994344?check_suite_focus=true#step:4:599):
```
  Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Operator '[]' is not applicable to an Undef Value. (file: /etc/puppetlabs/code/environments/production/modules/apt/manifests/source.pp, line: 102, column: 9) (file: /etc/puppetlabs/code/environments/production/modules/elastic_stack/manifests/repo.pp, line: 71) on node ubuntu1804-64.example.com
```
While the root problem is that a package is missing.

As it is right now, the PR fix the catalog but I can imagine cases where this will produce broken apt config.  I did a test for the above module but it seems to be okay (https://github.com/voxpupuli/puppet-elasticsearch/pull/1149) so maybe I am paranoid? :shrug: :smile:

2022-03-08 05:14 UTC, kenyon commented
@smortex in that elasticsearch test run, why is it complaining about source.pp line 102? That's just a variable assignment. 🤔

2022-03-08 05:52 UTC, smortex commented
> @smortex in that elasticsearch test run, why is it complaining about source.pp line 102? That's just a variable assignment. thinking

Line 102 in [the latest release](https://github.com/puppetlabs/puppetlabs-apt/blob/v8.3.0/manifests/source.pp#L102), but line 103 on `main` ATM:

```puppet
if ($facts['os']['distro']['codename'] in $_transport_https_releases) and $_location =~ /(?i:^https:\/\/)/ {
```

Without `lsb-release`, with facter 3, `$facts['os']['distro']` is `undef`

2022-03-15 11:55 UTC, root-expert commented
> > @smortex in that elasticsearch test run, why is it complaining about source.pp line 102? That's just a variable assignment. thinking
> 
> Line 102 in [the latest release](https://github.com/puppetlabs/puppetlabs-apt/blob/v8.3.0/manifests/source.pp#L102), but line 103 on `main` ATM:
> 
> ```puppet
> if ($facts['os']['distro']['codename'] in $_transport_https_releases) and $_location =~ /(?i:^https:\/\/)/ {
> ```
> 
> Without `lsb-release`, with facter 3, `$facts['os']['distro']` is `undef`

Ah I see you point. Yea that was the only part which the module doesn't fail. Failing directly on the `apt` class maybe it's too harsh? I would maybe opt out to fail per-class although not a strong opinion here.

2022-03-15 12:11 UTC, ekohl requested changes
Found a typo, other than that :+1:

2022-03-15 12:11 UTC, ekohl commented on manifests/source.pp
> +    if (fact('os.relese.major') in $_transport_https_releases) and $_location =~ /(?i:^https:\/\/)/ {
```suggestion
    if (fact('os.release.major') in $_transport_https_releases) and $_location =~ /(?i:^https:\/\/)/ {
```

2022-03-15 12:11 UTC, ekohl commented on manifests/source.pp
> +      $_release = fact('os.distro.codename')
Very strictly speaking, this line doesn't need to be modified since at this point you know it's available. But it works too.

2022-03-15 12:34 UTC, root-expert commented on manifests/source.pp
> +    if (fact('os.relese.major') in $_transport_https_releases) and $_location =~ /(?i:^https:\/\/)/ {
Thanks!

2022-03-15 12:38 UTC, ekohl approved these changes

2022-03-15 12:39 UTC, ekohl commented
A few times I've forgotten to merge after approving but having to wait for the tests. If I do, please ping me.

2022-03-15 15:50 UTC, smortex approved these changes
I am fine with this: maybe some edge case still need adjusting but it proves to improve the situation :+1:

2022-03-15 15:51 UTC, merged