(GH-1038) add support for `check-valid-until` configuration
puppetlabs/puppetlabs-apt pull request #1042
Opened 2022-07-28 10:30 UTC by david22swan

Add's additional configuration to `apt::source` to allow the user to specify whether or not to check if  the repository that they are accessing has a valid release ate.
Defaults to `True`

2022-07-28 10:31 UTC, david22swan commented
@fitzy101 Could you have a look at this and see if it was what you had in mind?

2022-07-28 10:50 UTC, david22swan commented on manifests/source.pp
> +        'Acquire::Check-Valid-Until'  => $check_valid_until? { true => undef, false => 'false' }
Yeh
The code get's confused otherwise and while it could probably be made to accept it(?), it would be unnecessarily complex.

2022-07-28 10:53 UTC, bastelfreak submitted a review, later dismissed

2022-08-03 02:20 UTC, fitzy101 requested changes
Hi @david22swan apologies for the delayed response. Thanks for looking at this configuration option. The current implementation doesn't quite address the problem, as the syntax isn't correct for setting the `check-valid-until` option inline.

If I manually set the value like in the commit, you can see the `apt update` command fails.
```
~ # cat /etc/apt/sources.list.d/debian-security-snapshot.list
deb [Acquire::Check-Valid-Until=false] https://snapshot.debian.org/archive/debian-security/20220612T175238Z/ bullseye-security main
~ # apt update
# ...
Hit:4 https://snapshot.debian.org/archive/debian-security/20220612T175238Z bullseye-security InRelease
Reading package lists... Done
E: Release file for https://snapshot.debian.org/archive/debian-security/20220612T175238Z/dists/bullseye-security/InRelease is expired (invalid since 44d 8h 26min 50s). Updates for this repository will not be applied.
# ...
```

The format should be `[check-valid-until=no]`, which you can see in the example below.

```
~ # cat /etc/apt/sources.list.d/debian-security-snapshot.list
deb [check-valid-until=no] https://snapshot.debian.org/archive/debian-security/20220612T175238Z/ bullseye-security main
~ # apt update
#...
Hit:4 https://snapshot.debian.org/archive/debian-security/20220612T175238Z bullseye-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
5 packages can be upgraded. Run 'apt list --upgradable' to see them.
```

2022-08-03 02:20 UTC, fitzy101 commented on manifests/source.pp
> +        'Acquire::Check-Valid-Until'  => $check_valid_until? { true => undef, false => 'false' }
```suggestion
        'check-valid-until'  => $check_valid_until? { true => undef, false => 'false' }
```

2022-08-03 08:17 UTC, david22swan commented on manifests/source.pp
> +        'Acquire::Check-Valid-Until'  => $check_valid_until? { true => undef, false => 'false' }
Updated

2022-08-03 08:27 UTC, david22swan commented
@fitzy101 That's the update made, thanks for getting back to me on it

2022-08-03 09:09 UTC, fitzy101 approved these changes

2022-08-03 09:09 UTC, fitzy101 commented
> @fitzy101 That's the update made, thanks for getting back to me on it

That’s great, thanks.

2022-08-03 10:01 UTC, LukasAud approved these changes

2022-08-03 10:02 UTC, merged