(GH-1057)Regex fix to allow dotted resources
puppetlabs/puppetlabs-apt pull request #1058
Opened 2022-08-30 12:05 UTC by LukasAud

Prior to this commit, one of our recent module updates introduced a
regex validation step for the resource names in our ppa.pp manifest
which would raise an issue if a valid resource name contained a dot (.).

This commit aims to slightly adjust the regex validation so that it
allows for dotted resource names. This PR should fix issue #1057.

2022-08-30 14:36 UTC, chelnak requested changes
Please can you update the unit tests to reflect this change?

2022-08-31 14:42 UTC, chelnak requested changes
Almost there! It's looking great, just a couple more observations.

2022-08-31 14:42 UTC, chelnak commented on spec/defines/ppa_spec.rb
> +  ].each do |inv_value|
This doesn't need to be different as it is scoped locally to the each. We can just keep it as `value` for simplicity. 

```suggestion
  ].each do |value|
```

2022-08-31 14:42 UTC, chelnak commented on spec/defines/ppa_spec.rb
> +      let(:title) { inv_value }
This doesn't need to be different as it is scoped locally to the each. We can just keep it as `value` for simplicity. 

```suggestion
      let(:title) { value }
```

2022-08-31 14:42 UTC, chelnak commented on spec/defines/ppa_spec.rb
> +      it { is_expected.to raise_error }
Let's be more explicit about the error we are looking for here.

You can use [this](https://github.com/puppetlabs/puppetlabs-apt/blob/65e03244552e8113b69f6ca5f4e6dc142251df0b/spec/defines/mark_spec.rb#L92) as an example.

2022-08-31 14:42 UTC, chelnak commented on spec/defines/ppa_spec.rb
> +      it { is_expected.not_to raise_error }
For the happy path, we could also check if the `exec` is being called with the resource title that we expect.

There are a few examples in this spec that use the `contains_exec` method.

2022-08-31 17:22 UTC, chelnak approved these changes
Fantastic thanks for putting in the effort!

2022-08-31 17:22 UTC, merged

2022-08-31 20:47 UTC, pmcmaw commented
Fixes #1057

2022-08-31 20:48 UTC, pmcmaw commented
Fixed #1057