ppa: include apt
puppetlabs/puppetlabs-apt pull request #1153
Opened 2023-12-13 22:35 UTC by kenyon

## Summary

This makes the ppa defined type easier to use without having to remember
to include the apt class. The original version of ppa.pp did an include
like this. See https://github.com/puppetlabs/puppetlabs-apt/pull/1152#issuecomment-1854787537

Fixes #1151

2023-12-13 22:39 UTC, bastelfreak approved these changes

2023-12-14 02:27 UTC, smortex requested changes
The parameter default value for `options` and `package_name` depend on `apt` being included before that class is used.

So this will likely to weird things.  Detecting the missing inclusion and reporting it still make sense, this is usually done by checking that the class exist and raising an error if not found, e.g. with nginx:

https://github.com/voxpupuli/puppet-nginx/blob/7f11626c052846999e494c5146f9e42d0db97ffe/manifests/resource/server.pp#L424-L426

2023-12-14 19:19 UTC, kenyon commented
@smortex do you have some reference on this behavior? I would think that the catalog compiler waits to resolve class variables until after it has loaded all of the classes.

2023-12-14 20:37 UTC, smortex commented
I don't have a reference at hand (not sure what to look for), but let me create a sample file that expose the "wrong" behavior:

```puppet
warning("foo=${foo}")
$foo = 'value'
warning("foo=${foo}")

class bar (
  $x,
) {
  warning("bar::x=${x}")
}

class baz (
  $x = $bar::x,
) {
  warning("baz::x=${x}")
}

class { 'baz':
}

class { 'bar':
  x => 'value',
}
```

```sh-session
romain@desktop-fln40kq /tmp % puppet apply -t foo.pp
Warning: Unknown variable: 'foo'. (file: /tmp/foo.pp, line: 1, column: 16)
Warning: Scope(Class[main]): foo=
Warning: Scope(Class[main]): foo=value
Warning: Unknown variable: 'bar::x'. (file: /tmp/foo.pp, line: 12, column: 8)
Warning: Scope(Class[Baz]): baz::x=
Warning: Scope(Class[Bar]): bar::x=value
Notice: Compiled catalog for desktop-fln40kq.lan in environment production in 0.01 seconds
Info: Using environment 'production'
Info: Applying configuration version '1702586183'
Notice: Applied catalog in 0.01 seconds
```

`foo=` and `baz::x=` do not have a value when evaluated, this produce a warning, but not an error.  IMHO, that behavior is not great, and at least when an undeclared value is used, setting a value to it later should raise an error to limit this kind of issues, but I guess its not a trivial change.

2023-12-14 21:10 UTC, kenyon commented
@smortex thanks. I'll just close this, but if someone else wants to add a missing inclusion detection, feel free.

2023-12-14 23:15 UTC, smortex commented
> @smortex thanks. I'll just close this, but if someone else wants to add a missing inclusion detection, feel free.

I opened https://github.com/puppetlabs/puppet/issues/9184, I feel like this is not great and should be improved.

2023-12-14 23:15 UTC, closed without merging